
# This is a basic workflow to help you get started with Actions

name: module8

# Controls when the workflow will run
on:
  push:
    branches:
      - 'main'
    paths:
      - 'C:/Users/vboxuser/terraform-infrastructure-as-code/module8**'
      
jobs:
  terraform:
    runs-on: ubuntu-latest
    
    name: 'MODULE8'
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      WORKING_DIR: C:/Users/vboxuser/terraform-infrastructure-as-code/module8
      
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@userOliv

      # Initialize Terraform
      - name: Terraform init
        id: init
        run: terraform init
        working-directory: ${{ env.WORKING_DIR }}
      
      # Generate a plan for Terraform changes
      - name: Terraform plan
        id: plan
        run: terraform plan
        working-directory: ${{ env.WORKING_DIR }}
      
      # Apply Terraform changes
      - name: Terraform apply
        id: apply
        run: terraform apply -auto-approve
        working-directory: ${{ env.WORKING_DIR }}
