#workflow navn:
name: init
on:
 #triggers the workflow on push or pull request events in the spesicified path( or in main branch)
    push:
      paths:
    #-	‘mappen klonned med repo depos in terraform/**’ 
      - 'C:/Users/vboxuser/terraform-infrastructure-as-code/**'
   # workflow dispatch allows the workflow to be runed manually from actions tab
    Workflow_dispatch:
    Jobs:
#workflow with a single job called “testmodule8”
    Resourcegroups:
#the type of runner( operative system) the job will run on
    runs-on: ubuntu-latest
    -name: ‘init’
    env:
    ARM_CLIENT_ID: ${{secrets.AZURE_CLIENT_ID}}
    ARM_CLIENT_SECRET: ${{secrets.AZURE_CLIENT_SECRET}}
    ARM_SUBSISCRIBTION_ID: ${{secrets.AZURE_ SUBSISCRIBTION _ID}} 
    ARM_TENANT_ID: ${{secrets.AZURE_TENANT_ID}}
    WORKING_DIR: .C:/Users/vboxuser/terraform-infrastructure-as-code/module8
#STEPS REPRESENT A SEQUENCE OF TASKS THAT WILL BE EXECUTED AS PART OF THE JOBB
-STEPS:
    #checks-out your repository under $github-workspace, so your job can access it
  -uses: actions/checkout@userOliv

    #Runs a single command using the runners shell
-name: ‘Terraform init’
id: init
run: terraform init 	
WORKING_DIR: ${{ env.WORKING_DIR }} 

-uses: actions/checkout@module8GithubActions
 -name: ‘Terraform plan’
   id: plan
  run: terraform plan 	
    working-directory: ${{ env.WORKING_DIR }}
   

 # -name: ‘Terraform apply’
 #  id: apply
 # run: terraform apply -auto-approve	
 # working-directory: ${{env.WORKING_DIR}}
